export ZSH="/home/clayton/.oh-my-zsh"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="$ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""

POWERLEVEL9K_CUSTOM_FEDORA_ICON="echo $'\uf4a2'"
POWERLEVEL9K_CUSTOM_FEDORA_ICON_BACKGROUND=069
POWERLEVEL9K_CUSTOM_FEDORA_ICON_FOREGROUND=015

POWERLEVEL9K_CUSTOM_NOW_PLAYING='~/.nowplaying'
POWERLEVEL9K_CUSTOM_NOW_PLAYING_BACKGROUND='blue'
POWERLEVEL9K_CUSTOM_NOW_PLAYING_FOREGROUND='black'

POWERLEVEL9K_VCS_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_VCS_SHORTEN_LENGTH=30

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=14'

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs custom_now_playing time)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir status)
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    caniuse
)

source $ZSH/oh-my-zsh.sh

alias frontend='cd ~/vendor-portal-frontend'
alias backend='cd ~/vendor-portal-backend'
alias shop='cd ~/shop'
alias cd-nvim='cd ~/.config/nvim'

fpath=($fpath "/home/clayton/.zfunctions")

  # Set Spaceship ZSH as a prompt
  autoload -U promptinit; promptinit
  prompt spaceship

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
